== Требования к проекту

=== Требования к фильтрации
Сервис должен поддерживать фильтрацию данных по всем доступным критериям (логическое И).

=== Требования к пагинации
* Запрос
** номер страницы
** размер страницы

* Ответ
** номер страницы
** размер страницы
** булевый признак наличия следующей страницы

* Размер страницы (количество записей)
** 10
** 20
** 100

=== Связывание данных
Связывание данных осуществляйте с помощью JAXB.

=== Реализуйте следующие сервисы
* Логгер
** Все ошибки при работе с API должны логироваться
** Реализуйте несколько уровней логирования
*** ALL- все события
*** DEBUG- отладочные сообщения
*** ERROR- сообщения об ошибках
** Поддержите вывод
*** В консоль
*** В текстовый файл
** Поддержите формат события
*** Дата и время события в формате ISO-8601 (паттерн yyyy-MM-dd'T'HH:mm:ss.SSSZ), уровень логирования, текст сообщения
** Реализуйте настройку логгера (уровень логирования, таргетирование) через property файл приложения
* Аудит сервис
** Любое изменение сущности "договор" должно сопровождаться вызовом сервиса Аудита
** Сервис Аудита считывает метаинформацию из аннотации и принимает решение, какой тип сущности необходимо обработать. Далее формируется событие аудита.
** Формат события представлен в файле *QuestionAuditEvent.xml* пакета sbp.sberuniversity.jcore.draft.services.audit.sample
** Событие должно сохраняться в текстовый файл с именем *AuditEvents_ENTITYNAME_yyyy-MM-dd.log*
* Сервис получения возможных действий по договору
** На основе текущего статуса договора вычисляется список возможных действий над ним
*** Черновик -> Обновить, Подписать, Отменить
*** Частично подписан -> Подписать
*** Подписан -> Оплатить
*** Заключен -> [нет доступных действий]
*** Отменен -> [нет доступных действий]
* Сервис криптоопераций
** По идентификатору субъекта сервис позволяет проверить наличие у субъекта сертификата ЭЦП
** Позволяет сгенерировать ЭЦП субъекту и возвращает UUID криптопрофиля
** Позволяет подписать договор используя идентификатор договора, идентификатор субъекта и UUID криптопрофиля
* Сервис оплаты
** Принимает на вход идентификатор договора и субъекта, возвращает булевый признак успеха операции оплаты
* Маппинг- сервис
** Реализовать двунаправленный маппинг: DAO в MODEL и обратно

=== Прочие требования
* Реализуйте аннотацию
** Тип- маркерная аннотация для методов, которые изменяют состояние сущностей в сервисном слое
** При обращении к сервису Аудита проверяйте наличие аннотации в вызывающем методе
* Используйте generic и widlcards везде, где это оправдано
* Новые классы должны быть размещены в соответствующих пакетах
* Выделите и используйте свои исключения, унаследовав их от родительского Exception
* Внедрение зависимостей осуществляйте через DIContainer (см. пакет sbp.sberuniversity.jcore.draft.core.di)
* Получение настроечных параметров сервиса выполняйте с помощью ConfigService (см. пакет sbp.sberuniversity.jcore.draft.host.config.ConfigService)
* Сервисный слой должен быть покрыт юнит- тестами
* При написании кода придерживайтесь кодстайла проекта
* Сопроводите свое решение примерами запросов к REST API (см. README.MD)
